### ISSUE TITLE
Closed problem

### ISSUE THREAD

**Issue by kronic** [abiliojr/fts5-snowball#2] opened 2016-11-09 22:09 UTC
I am compile and using c#.
after close connectin get error memory problem. 
I have problem call destroySnowball many thread.
http://system.data.sqlite.org/index.html/info/b4ef73b33a7ce8d9

**Comment by abiliojr** [comment] 2021-04-17 05:00
Closed as duplicate of #3

**Closed as completed by abiliojr** 2021-04-17 05:00 UTC
